language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - root=`pwd`
  - sudo apt-add-repository -y ppa:gijzelaar/opencv2.4
  - sudo apt-get update
  - sudo apt-get install -qq python-numpy python-opencv python-pyfann
    python-sklearn python-yaml

install:
  - cd $root/nbclassify/
  - pip install -r requirements.txt
  - pip install https://github.com/naturalis/imgpheno/archive/master.zip

before_script:
  - cd $root/nbclassify/

script:
  - make test
