language: python

python:
  - "2.7"

install:
  - sudo apt-get install python-dev python-pip python-numpy libfann2
    python-pyfann python-numpy python-sqlalchemy libopencv-core2.3 python-opencv
  - sudo pip install flickrapi pyyaml
  - git clone https://github.com/naturalis/imgpheno.git
  - cd imgpheno/
  - sudo python setup.py install

script:
  - cd nbclassify/tests/; make
